const template = `
There were the following issues with this Pull Request
<PLACEHOLDER>
You need to change the Pull request title to comply with the \
repository contributing guidelines.
--------
🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report \
issues [here][issues].
Happy coding!
[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/rittme/conventional-pr-app
[issues]: https://github.com/z0al/conventional-pr-app/issues
`

/**
 * Formats array of commits warnings/errors as GitHub comment
 *
 * @param {Array} report
 */
function format (errors, warnings) {
  let message = ''

  message += errors.map(e => `  - ✖ ${e.message}\n`).join('')
  message += warnings.map(w => `  - ⚠ ${w.message}\n`).join('')

  return template.replace('<PLACEHOLDER>', message)
}

module.exports = format
